-- Migration 0001: Core multi-tenant schema with RLS
-- DECISÃO: Billing/credits por tenant, não por restaurante (1.2.1)
-- DECISÃO: Soft-delete (deleted_at) em tenants/restaurants
-- DECISÃO: grace_until para período de graça de billing
-- DECISÃO: RLS em TODAS as tabelas com tenant_id
-- DECISÃO: platform_settings singleton só super-admin
-- DECISÃO: event_log append-only

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- PLATAFORMA (singleton, só super-admin)
-- ============================================================================

create table platform_settings (
  id smallint primary key generated by default as identity,
  constraint singleton_check check (id = 1),

  -- Seleção de gateway (alternável no painel)
  subscription_provider text not null check (subscription_provider in ('zumbopay','paysuite','mock')) default 'zumbopay',
  credits_provider text not null check (credits_provider in ('zumbopay','paysuite','mock')) default 'paysuite',

  -- (B) SEGREDOS de gateway/email — cifrados (Supabase Vault), nunca ao client nem em texto puro
  zumbopay_api_key text,
  zumbopay_webhook_secret text,
  zumbopay_wallet_id text,
  zumbopay_merchant_id text,
  paysuite_api_key text,
  paysuite_webhook_secret text,
  resend_api_key text,

  -- (A) IDs PÚBLICOS de tracking — vão ao client via get_public_tracking()
  gtm_container_id text,
  meta_pixel_id text,
  ga4_measurement_id text,
  gads_conversion_id text,
  gads_conversion_label text,

  -- (B) SEGREDOS de tracking — só server-side
  meta_capi_token text,
  gads_developer_token text,

  updated_at timestamptz not null default now()
);

-- Insert singleton row
insert into platform_settings (id) values (1);

-- RLS: platform_settings — sem policies: anon e authenticated comuns não acedem
alter table platform_settings enable row level security;

-- ============================================================================
-- TENANTS
-- ============================================================================

create table tenants (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  slug text not null unique,

  plan text not null check (plan in ('base','pro','premium')) default 'base',
  status text not null check (status in ('trial','active','past_due','canceled')) default 'trial',

  trial_ends_at timestamptz not null default (now() + interval '14 days'),
  grace_until timestamptz,   -- Período de graça quando past_due (1.2.5)
  deleted_at timestamptz,    -- Soft-delete (1.2.7)

  created_at timestamptz not null default now()
);

-- ============================================================================
-- MEMBERSHIPS
-- ============================================================================

create table memberships (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  user_id uuid not null,  -- auth.users.id
  role text not null default 'owner' check (role in ('owner','admin','member')),
  created_at timestamptz not null default now(),

  unique(tenant_id, user_id)
);

-- ============================================================================
-- HELPER FUNCTIONS (depois de memberships existir)
-- ============================================================================

create or replace function public.auth_tenant_ids()
returns setof uuid language sql stable security definer set search_path = public as $$
  select tenant_id from memberships where user_id = auth.uid();
$$;

-- ============================================================================
-- RLS — tabelas com tenant_id (padrão 16.1)
-- ============================================================================

alter table tenants enable row level security;
create policy "tenant_isolation" on tenants for all to authenticated
  using (id in (select auth_tenant_ids()))
  with check (id in (select auth_tenant_ids()));

alter table memberships enable row level security;
create policy "tenant_isolation" on memberships for all to authenticated
  using (tenant_id in (select auth_tenant_ids()))
  with check (tenant_id in (select auth_tenant_ids()));

-- ============================================================================
-- RESTAURANTS
-- ============================================================================

create table restaurants (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references tenants(id) on delete cascade,
  name text not null,
  slug text not null,

  logo_url text,
  brand_colors jsonb,
  photos jsonb,

  open_hour int not null default 15,
  close_hour int not null default 23,
  timezone text not null default 'Africa/Maputo',

  deleted_at timestamptz,
  created_at timestamptz not null default now(),

  unique(tenant_id, slug)
);

alter table restaurants enable row level security;
create policy "tenant_isolation" on restaurants for all to authenticated
  using (tenant_id in (select auth_tenant_ids()))
  with check (tenant_id in (select auth_tenant_ids()));

-- ============================================================================
-- CREDIT_WALLETS
-- ============================================================================

create table credit_wallets (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null unique references tenants(id) on delete cascade,
  balance int not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

alter table credit_wallets enable row level security;
create policy "tenant_isolation" on credit_wallets for all to authenticated
  using (tenant_id in (select auth_tenant_ids()))
  with check (tenant_id in (select auth_tenant_ids()));

-- ============================================================================
-- EVENT_LOG (append-only)
-- ============================================================================

create table event_log (
  id bigserial primary key,
  tenant_id uuid references tenants(id) on delete set null,
  type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table event_log enable row level security;
create policy "tenant_isolation" on event_log for all to authenticated
  using (tenant_id in (select auth_tenant_ids()))
  with check (tenant_id in (select auth_tenant_ids()));

-- ============================================================================
-- RPC: create_tenant
-- Cria atomicamente tenant + membership + restaurant + credit_wallet
-- ============================================================================

create or replace function public.create_tenant(p_name text, p_user_id uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_tenant_id uuid;
  v_restaurant_id uuid;
  v_wallet_id uuid;
  v_membership_id uuid;
begin
  insert into tenants (name, slug, plan, status, trial_ends_at)
  values (
    p_name,
    lower(regexp_replace(p_name, '[^a-z0-9]+', '-', 'g')) || '-' || substr(md5(random()::text), 1, 8),
    'base',
    'trial',
    now() + interval '14 days'
  )
  returning id into v_tenant_id;

  insert into memberships (tenant_id, user_id, role)
  values (v_tenant_id, p_user_id, 'owner')
  returning id into v_membership_id;

  insert into restaurants (tenant_id, name, slug, open_hour, close_hour, timezone)
  values (v_tenant_id, p_name, 'main', 15, 23, 'Africa/Maputo')
  returning id into v_restaurant_id;

  insert into credit_wallets (tenant_id, balance)
  values (v_tenant_id, 0)
  returning id into v_wallet_id;

  return v_tenant_id;
end;
$$;

grant execute on function public.create_tenant(text, uuid) to authenticated;

-- ============================================================================
-- INDEXES
-- ============================================================================

create index idx_memberships_user_id on memberships(user_id);
create index idx_tenants_slug on tenants(slug);
create index idx_restaurants_tenant_id on restaurants(tenant_id);
create index idx_credit_wallets_tenant_id on credit_wallets(tenant_id);
create index idx_event_log_tenant_id on event_log(tenant_id);
create index idx_event_log_created_at on event_log(created_at);
